export { default as Landing } from './landing'
export { default as Home } from './home'
export { default as Intro } from './intro'
export { default as Quiz } from './quiz'
export { default as Question } from './question'
